name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  #checkout the code
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci     #equivalent to npm install but cleaner
      - run: npm test
      - run: npm run build